class Mail{
public static void main(String[] args){
String kavya="kavyas1@gmail.com";
String roshni="roshni2@gmail@gmail.com";
String pallavi="pallavigh34@gmail.com";
String deepu="deghtyy34@gmail.com";
String sangeeth="sangeeth220@gmail@gmail.com";
String arjuna="arjunas5@gmail.com";
String rajkesh="rajmehta@gmail.com";
String priyanka="priyanaka@gmail.com";
String sonu="sonu47@gmail.com";
String kishan="kishan51@gmail@gmail.com";
String hima="hima901@gmail.com";
String ganavi="ganavi56@gmail.com";
String suma="suma8@gmail.com";
String sudha="sudha67@gmail.com";
String preethu="preethu77@gmail7@gmail.com";
String[] email={kavya,roshni,pallavi,deepu,sangeeth,arjuna,rajkesh,priyanka,sonu,kishan,hima,ganavi,suma,sudha,preethu};
int totalmails=email.length;
		String ref=email[0];
		String ref1=email[1];
		String ref2=email[2];
		String ref3=email[3];
		String ref4=email[4];
		String ref5=email[5];
		String ref6=email[6];
		String ref7=email[7];
		String ref8=email[8];
		String ref9=email[9];
		String ref10=email[10];
		String ref11=email[11];
		String ref12=email[12];
		String ref13=email[13];
		String ref14=email[14];
		System.out.println(ref);
		System.out.println(ref1);
		System.out.println(ref2);
		System.out.println(ref3);
		System.out.println(ref4);
		System.out.println(ref5);
		System.out.println(ref6);
		System.out.println(ref7);
		System.out.println(ref8);
		System.out.println(ref9);
		System.out.println(ref10);
		System.out.println(ref11);
		System.out.println(ref12);
		System.out.println(ref13);
		System.out.println(ref14);
    }
}